### ISSUE TITLE
Wrong link to AI City Challenge data in slides

### ISSUE THREAD

**Issue by oscmansan** [mcv-m6-video/class2020#4]
In the [slides](https://docs.google.com/presentation/d/14ndLH4ppbxUlnwYOnQXj3HwXsTZJ-iURXi2tjlyI1Ew/edit?usp=sharing) you explain that we are going to use the data from the **2020** AI City Challenge, but the link you provide in slide 8 is for the **2019** edition data. Could you update the links in the slides? Thanks!

@xavigiro @jrhupc

**Comment by jrhupc** [comment]
Hi Oscar,

The data for the 2020 challenge is the same as the data for the 2019. You can safely use it for this year.

Regards,

**Comment by jrhupc** [comment]
Hi again, 

I have double check the data and even though the sequences are the same, there is ground truth in the 2020 test sequences also (and some differences in the homography matrices). Therefore, I have created a link in my google slides to download the dataset. Here it is:

https://drive.google.com/file/d/16mbwvYmDBWI4q1BGcSnwJuqhZ4dj8tus/view?usp=sharing

I will also update the links in the slides.

Regards,

**Comment by jrhupc** [comment]
Links for week 5 updated in google slides. The entire dataset is 15GB so be patient with the download. Let me know if you find any problems.

**Comment by oscmansan** [comment]
Thanks @jrhupc!
