### ISSUE TITLE
Ground truth for single camera tracking

### ISSUE THREAD

**Issue by sergiocasaspastor** [mcv-m6-video/class2020#5]
Hi. We have a doubt about single camera tracking. The gt txt files provided in the dataset contain only annotations about the vehicles that pass through 2 cameras. Therefore, the vehicles are not annotated in the frames where only one camera is capturing them. That will affect the training and the values of  of mAP and idf1 will be lower. We do not know if that is part of the complexity of the first task and we have to try to propose a solution for that, or if we have to train only with the vehicles detected in the ground truth.
Maybe we are wrong and there is a different way to proceed for single camera tracking. 
Best regards,
Team 5

**Comment by jrhupc** [comment]
Hello Sergio,

You are right, there is no GT for moving cars provided in the AI city challenge sequences and, unfortunately, that will indeed affect the IDF1 measures. However, all teams will be affected equally and we believe the easiest way to cope with it is just use it as it is. 

Regards,
